version: "3"


# This is the base docker compose config. The main purpose is to:
# 1. List all of the services & dbs in the system
# 2. Specify the docker image / build context for every service
# 3. Make sure all the components are in the same virtual network "spider"
# 4. Make sure all the components are under the same environment variables "SPIDER_*"
# 5. Make sure all the components have the right dependencies on each other
# 6. NO volume mounting
# 7. NO port publishing for internal components
# 8. NO "restart:always" kind of configs that handle fail-over


services:
  config_gateway_service:
    build:
      context: config_gateway_service
    networks:
      spider:
    environment:
      - SPIDER_RUNTIME_STAGE=${SPIDER_RUNTIME_STAGE}
      - SPIDER_RUNTIME_MODE=${SPIDER_RUNTIME_MODE}

  policy_gateway_service:
    build:
      context: policy_gateway_service
    networks:
      spider:
    environment:
      - SPIDER_RUNTIME_STAGE=${SPIDER_RUNTIME_STAGE}
      - SPIDER_RUNTIME_MODE=${SPIDER_RUNTIME_MODE}

  action_gateway_service:
    build:
      context: action_gateway_service
    networks:
      spider:
    environment:
      - SPIDER_RUNTIME_STAGE=${SPIDER_RUNTIME_STAGE}
      - SPIDER_RUNTIME_MODE=${SPIDER_RUNTIME_MODE}


networks:
  spider: